// src/pages/Experience.svelte
<script>
  import {
    Timeline,
    TimelineItem,
    Card,
    Blockquote,
    List,
    Li,
    Heading
  } from "flowbite-svelte";
</script>

<span>
  <div class="grid grid-cols-3 gap-4">
    <div class="col-start-2">
      <Timeline order="vertical">
        <TimelineItem title="Analyst  & Software Developer at Afliant s.r.l">
          <Blockquote size="xs" class="mb-4">October 2024 - Present</Blockquote>
          <Card class="p-4 sm:p-6 md:p-8 mb-4" size="xl">
            <Heading tag="h5"
              class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"
            >
              Cisalfa Sport
            </Heading>
            <List tag="ul" class="space-y-1 text-gray-500 dark:text-gray-400">
              <Li>
                Functional analysis of the flows requested by the customer to
                implement the new OMS system for managing shipments
              </Li>
            </List>
          </Card>
          <Card class="p-4 sm:p-6 md:p-8 mb-4" size="xl">
            <Heading tag="h5"
              class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"
            >
              Trentino electronic school register system
            </Heading>
            <List tag="ul" class="space-y-1 text-gray-500 dark:text-gray-400">
              <Li>
                Development of microservice solutions as a Full Stack Developer
              </Li>
            </List>
          </Card>
        </TimelineItem>

        <TimelineItem title="Software Developer at CherryChain s.r.l">
          <Blockquote size="xs" class="mb-4"
            >August 2020 - October 2024</Blockquote
          >
          <Card class="p-4 sm:p-6 md:p-8 mb-4" size="xl">
            <Heading tag="h5"
              class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"
            >
              Loyalty customer management for DAO partners
            </Heading>
            <List tag="ul" class="space-y-1 text-gray-500 dark:text-gray-400">
              <Li
                >Development of microservice solutions as a Full Stack
                Developer;</Li
              >
              <Li
                >Native Android application development for the release of
                loyalty cards and retrieval of personal data via CIE 3.0;</Li
              >
              <Li
                >Prototyping and implementation of RESTful API for third
                parties;</Li
              >
              <Li
                >Supervisor and implementer of infrastructure change using
                Terraform;</Li
              >
              <Li
                >Transition from a system managed by AWS EC2 servers and Docker
                Swarm to an AWS ECS system and Application Load Balancer;</Li
              >
            </List>
          </Card>

          <Card class="p-4 sm:p-6 md:p-8 mb-4" size="xl">
            <Heading tag="h5"
              class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"
            >
              Real-time consumption display system for Dolomiti Energia
            </Heading>
            <List tag="ul" class="space-y-1 text-gray-500 dark:text-gray-400">
              <Li
                >RPA development for extraction, transformation, and loading of
                consumption data per user on an MSSQL database;
              </Li>
              <Li
                >Development of RESTful API service for retrieval of consumption
                data;</Li
              >
            </List>
          </Card>
        </TimelineItem>
        <TimelineItem title="Bachelor Degree at University of Trento">
          <Blockquote size="xs">September 2017 - September 2020</Blockquote>
        </TimelineItem>
      </Timeline>
    </div>
  </div>
</span>

<style>
</style>

// src/components/Experience.vue
<script setup>
import {
  FwbTimeline,
  FwbTimelineBody,
  FwbTimelineContent,
  FwbTimelineItem,
  FwbTimelinePoint,
  FwbTimelineTime,
  FwbTimelineTitle,
  FwbCard
} from 'flowbite-vue'
</script>

<template>
  <div class="grid grid-cols-3 gap-4">
    <div class="col-start-2">
      <fwb-timeline>
        <fwb-timeline-item>
          <fwb-timeline-point />
          <fwb-timeline-content>
            <fwb-timeline-time class="text-gray-300 ">
              October 2024 - Present
            </fwb-timeline-time>
            <fwb-timeline-title >
              Analyst & Software Developer at Afliant s.r.l
            </fwb-timeline-title>
            <fwb-timeline-body>
              <fwb-card class="w-sm mb-4 bg-gray-900 dark:bg-teal-600">
                <div class="p-5">
                  <h5 class="mb-2 text-2xl font-bold tracking-tight text-white">
                    Cisalfa Sport
                  </h5>
                  <p class="font-normal text-gray-400 dark:text-gray-200">
                    Functional analysis of the flows requested by the customer to
                    implement the new OMS system for managing shipments
                  </p>
                </div>
              </fwb-card>
              <fwb-card class="w-sm mb-4 bg-gray-900 dark:bg-teal-600">
                <div class="p-5">
                  <h5 class="mb-2 text-2xl font-bold tracking-tight text-white">
                    Trentino electronic school register system
                  </h5>
                  <p class="font-normal text-gray-400 dark:text-gray-200">
                    Development of microservice solutions as a Full Stack Developer
                  </p>
                </div>
              </fwb-card>
            </fwb-timeline-body>
          </fwb-timeline-content>
        </fwb-timeline-item>
        <fwb-timeline-item>
          <fwb-timeline-point />
          <fwb-timeline-content>
            <fwb-timeline-time>
              August 2020 - October 2024
            </fwb-timeline-time>
            <fwb-timeline-title>
              Software Developer at CherryChain s.r.l
            </fwb-timeline-title>
            <fwb-timeline-body>
              <fwb-card class="w-sm mb-4 bg-gray-900 dark:bg-teal-600">
                <div class="p-5">
                  <h5 class="mb-2 text-2xl font-bold tracking-tight text-white">
                    Loyalty customer management for DAO partners
                  </h5>
                  <ul>
                    <li class=" text-gray-400 dark:text-gray-200">Development of microservice solutions as a Full Stack Developer;
                    </li>
                    <li class=" text-gray-400 dark:text-gray-200">Native Android application development for the release of
                      loyalty cards and retrieval of personal data via CIE 3.0;
                    </li>
                    <li class=" text-gray-400 dark:text-gray-200">Prototyping and implementation of RESTful API for third
                      parties;
                    </li>
                    <li class=" text-gray-400 dark:text-gray-200">Supervisor and implementer of infrastructure change using
                      Terraform;
                    </li>
                    <li class=" text-gray-400 dark:text-gray-200">Transition from a system managed by AWS EC2 servers and Docker
                      Swarm to an AWS ECS system and Application Load Balancer;</li>
                  </ul>
                </div>
              </fwb-card>
              <fwb-card class="w-sm mb-4 bg-gray-900 dark:bg-teal-600">
                <div class="p-5">
                  <h5 class="mb-2 text-2xl font-bold tracking-tight text-white">
                    Real-time consumption display system for Dolomiti Energia
                  </h5>
                  <ul>
                    <li class=" text-gray-400 dark:text-gray-200">RPA development for extraction, transformation, and loading of
                      consumption data per user on an MSSQL database;
                    </li>
                    <li class=" text-gray-400 dark:text-gray-200">Development of RESTful API service for retrieval of consumption
                      data;
                    </li>
                  </ul>
                </div>
              </fwb-card>
            </fwb-timeline-body>
          </fwb-timeline-content>
        </fwb-timeline-item>
        <fwb-timeline-item>
          <fwb-timeline-point />
          <fwb-timeline-content>
            <fwb-timeline-time>
              September 2017 - September 2020
            </fwb-timeline-time>
            <fwb-timeline-title>
              Bachelor Degree at University of Trento
            </fwb-timeline-title>
            <fwb-timeline-body>
            </fwb-timeline-body>
          </fwb-timeline-content>
        </fwb-timeline-item>
      </fwb-timeline>
    </div>
  </div>

</template>

<style></style>
